version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      OLLAMA_HOST: '0.0.0.0:11434'
      OLLAMA_ORIGINS: '*'
      OLLAMA_NUM_THREADS: '2'
      OLLAMA_CUDA: '1'
      OLLAMA_MAX_LOADED: '2'
      HUGGING_FACE_TOKEN: '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'  # Reemplaza con tu token real
    volumes:
      - './Product Sheets Pharmaceutics:/app/Product Sheets Pharmaceutics'